=== xl666/jaca-ddm/node0/config/sys.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://uv.mx/hlimon"
xmlns="http://uv.mx/hlimon"
elementFormDefault="qualified">

<xs:element name="config">
  <xs:complexType>
    <xs:sequence>

      <xs:element name="node0" minOccurs="0">
	  <xs:complexType>
	     <xs:all>
		  <xs:element name="name" type="xs:string" default="node0" minOccurs="0"/>
		  <xs:element name="ip" type="xs:string" default="localhost"/>
	     </xs:all>
	  </xs:complexType>
      </xs:element>


      <xs:element name="nodes">
	<xs:complexType>
	  <xs:sequence>
	    <xs:element name="node" type="node" maxOccurs="unbounded"/> 
	  </xs:sequence>
	</xs:complexType>	
      </xs:element>


      <xs:element name="strategy">
	<xs:complexType>
	  <xs:all>
	    <xs:element name="file" type="xs:string"/>
	    <xs:element name="params" type="paramsTemplate" minOccurs="0"/>
	  </xs:all>
	</xs:complexType>	
      </xs:element>

      <xs:element name="distribution">
	<xs:complexType>
	  <xs:sequence>
	    <xs:element name="agents" maxOccurs="unbounded">
	      <xs:complexType>
		<xs:all>
		  <xs:element name="program" type="xs:string"/>
		  <xs:element name="node" type="xs:string"/>
		  <xs:element name="number" type="xs:decimal"  minOccurs="0" default="1"/>
		</xs:all>
	      </xs:complexType>	
	    </xs:element>
	  </xs:sequence>
	</xs:complexType>	
      </xs:element>

      <xs:element name="evaluation">
	<xs:complexType>
	  <xs:all>
	    <xs:element name="name" type="xs:string"/>
	    <xs:element name="typeDataSource" type="xs:string"/>
	    <xs:element name="params" type="paramsTemplate"/>
	  </xs:all>
	</xs:complexType>	
      </xs:element>
      
      <xs:element name="reps" type="xs:decimal"  minOccurs="0" default="1"/>

    </xs:sequence>
  </xs:complexType>
</xs:element>


<xs:complexType name="node">
  <xs:all>
    <xs:element name="name" type="xs:string"/>
    <xs:element name="ip" type="xs:string"/>
    <xs:element name="user" type="xs:string"  minOccurs="0"/>
    <xs:element name="pass" type="xs:string" minOccurs="0"/>
    <xs:element name="file" type="xs:string"/>
  </xs:all>
</xs:complexType>	

<xs:complexType name="paramTemplate">
  <xs:all>
    <xs:element name="name" type="xs:string"/>
    <xs:element name="value" type="xs:string"/>
    <xs:element name="type" type="xs:string"/>
  </xs:all>
</xs:complexType>	

<xs:complexType name="paramsTemplate">
  <xs:sequence>
    <xs:element name="param" type="paramTemplate" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>	



</xs:schema>

=== xl666/jaca-ddm/sampleProtocols/counterGPU/counterGPU.xml
<?xml version="1.0"?>
<config xmlns="http://uv.mx/hlimon"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://uv.mx/hlimon sys.xsd">

  <name>CounterGPU</name>

  <agents>
    <agent>
      <program>contactPerson</program>
      <file>../sampleProtocols/counterGPU/contactPerson.asl</file>
    </agent>
    <agent>
      <program>worker</program>
      <file>../sampleProtocols/counterGPU/worker.asl</file>
    </agent>
    <agent>
      <program>roundController</program>
      <file>../sampleProtocols/counterGPU/roundController.asl</file>
    </agent>
  </agents>

  <params>
    <param>
      <name>Pruning</name>
      <type>boolean</type>
    </param>
    <param>
      <name>Init Percentage</name>
      <type>double</type>
    </param>
    <param>
      <name>Max Rounds</name>
      <type>int</type>
    </param>
    <param>
      <name>Test Percentaje For Rounds</name>
      <type>double</type>
    </param>
    <param>
      <name>Change step</name>
      <type>double</type>
    </param>
    <param>
      <name>Initial counter examples filtering</name>
      <type>double</type>
    </param>
    <param>
      <name>Counter examples filtering step</name>
      <type>double</type>
    </param>
    <param>
      <name>Min counters to filter</name>
      <type>int</type>
    </param>
  </params>

</config>

=== xl666/jaca-ddm/sampleProtocols/splitting/splitting.xml
<?xml version="1.0"?>
<config xmlns="http://uv.mx/hlimon"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://uv.mx/hlimon sys.xsd">

<name>Splitting</name>

<agents>
  <agent>
    <program>contactPerson</program>
    <file>../sampleProtocols/splitting/contactPerson.asl</file>
  </agent>
   <agent>
    <program>splitter</program>
    <file>../sampleProtocols/splitting/splitter.asl</file>
  </agent>
</agents>
  <params>
    <param>
      <name>Threads per node</name>
      <type>int</type>
    </param>
    <param>
      <name>Classifier</name>
      <type>string</type>
    </param>
    <param>
      <name>Stratify</name>
      <type>boolean</type>
    </param>
  </params>
</config>
