=== xl666/jaca-ddm/node0/config/sys.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://uv.mx/hlimon"
xmlns="http://uv.mx/hlimon"
elementFormDefault="qualified">

<xs:element name="config">
  <xs:complexType>
    <xs:sequence>

      <xs:element name="node0" minOccurs="0">
	  <xs:complexType>
	     <xs:all>
		  <xs:element name="name" type="xs:string" default="node0" minOccurs="0"/>
		  <xs:element name="ip" type="xs:string" default="localhost"/>
	     </xs:all>
	  </xs:complexType>
      </xs:element>


      <xs:element name="nodes">
	<xs:complexType>
	  <xs:sequence>
	    <xs:element name="node" type="node" maxOccurs="unbounded"/> 
	  </xs:sequence>
	</xs:complexType>	
      </xs:element>


      <xs:element name="strategy">
	<xs:complexType>
	  <xs:all>
	    <xs:element name="file" type="xs:string"/>
	    <xs:element name="params" type="paramsTemplate" minOccurs="0"/>
	  </xs:all>
	</xs:complexType>	
      </xs:element>

      <xs:element name="distribution">
	<xs:complexType>
	  <xs:sequence>
	    <xs:element name="agents" maxOccurs="unbounded">
	      <xs:complexType>
		<xs:all>
		  <xs:element name="program" type="xs:string"/>
		  <xs:element name="node" type="xs:string"/>
		  <xs:element name="number" type="xs:decimal"  minOccurs="0" default="1"/>
		</xs:all>
	      </xs:complexType>	
	    </xs:element>
	  </xs:sequence>
	</xs:complexType>	
      </xs:element>

      <xs:element name="evaluation">
	<xs:complexType>
	  <xs:all>
	    <xs:element name="name" type="xs:string"/>
	    <xs:element name="typeDataSource" type="xs:string"/>
	    <xs:element name="params" type="paramsTemplate"/>
	  </xs:all>
	</xs:complexType>	
      </xs:element>
      
      <xs:element name="reps" type="xs:decimal"  minOccurs="0" default="1"/>

    </xs:sequence>
  </xs:complexType>
</xs:element>


<xs:complexType name="node">
  <xs:all>
    <xs:element name="name" type="xs:string"/>
    <xs:element name="ip" type="xs:string"/>
    <xs:element name="user" type="xs:string"  minOccurs="0"/>
    <xs:element name="pass" type="xs:string" minOccurs="0"/>
    <xs:element name="file" type="xs:string"/>
  </xs:all>
</xs:complexType>	

<xs:complexType name="paramTemplate">
  <xs:all>
    <xs:element name="name" type="xs:string"/>
    <xs:element name="value" type="xs:string"/>
    <xs:element name="type" type="xs:string"/>
  </xs:all>
</xs:complexType>	

<xs:complexType name="paramsTemplate">
  <xs:sequence>
    <xs:element name="param" type="paramTemplate" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>	



</xs:schema>

=== xl666/jaca-ddm/sampleProtocols/centralizedBagging/centralizedBagging.xml
<?xml version="1.0"?>
<config xmlns="http://uv.mx/hlimon"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://uv.mx/hlimon sys.xsd">

  <name>Centralized Bagging</name>

  <agents>
    <agent>
      <program>contactPerson</program>
      <file>../sampleProtocols/centralizedBagging/contactPerson.asl</file>
    </agent>
  </agents>

  <params>
    <param>
      <name>Number of models</name>
      <type>int</type>
    </param>
    <param>
      <name>Threads</name>
      <type>int</type>
    </param>
    <param>
      <name>Classifier</name>
      <type>string</type>
    </param>
    <param>
      <name>Classifier parameters</name>
      <type>string</type>
    </param>
  </params>

</config>

=== xl666/jaca-ddm/sampleProtocols/roundCounter/roundCounter.xml
<?xml version="1.0"?>
<config xmlns="http://uv.mx/hlimon"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://uv.mx/hlimon sys.xsd">

<name>Round Counter</name>

<agents>
  <agent>
    <program>contactPerson</program>
    <file>../sampleProtocols/roundCounter/contactPerson.asl</file>
  </agent>
   <agent>
    <program>worker</program>
    <file>../sampleProtocols/roundCounter/worker.asl</file>
  </agent>
   <agent>
    <program>roundController</program>
    <file>../sampleProtocols/roundCounter/roundController.asl</file>
  </agent>
</agents>

<params>
  <param>
    <name>Max Rounds</name>
    <type>int</type>
  </param>
  <param>
    <name>Init Percentage</name>
    <type>double</type>
  </param>
   <param>
    <name>Test Percentaje For Rounds</name>
    <type>double</type>
  </param>
   <param>
    <name>Change step</name>
    <type>double</type>
  </param>
</params>

</config>

=== xl666/jaca-ddm/sampleProtocols/centralizing/centralizing.xml
<?xml version="1.0"?>
<config xmlns="http://uv.mx/hlimon"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://uv.mx/hlimon sys.xsd">

<name>Centralizing</name>

<agents>
  <agent>
    <program>contactPerson</program>
    <file>../sampleProtocols/centralizing/contactPerson.asl</file>
  </agent>
   <agent>
    <program>sender</program>
    <file>../sampleProtocols/centralizing/sender.asl</file>
  </agent>
</agents>

<params>
  <param>
    <name>Pruning</name>
    <type>boolean</type>
  </param>
    <param>
    <name>Classifier</name>
    <type>string</type>
  </param>
</params>

</config>

=== xl666/jaca-ddm/sampleProtocols/tripletTree/tripletTree.xml
<?xml version="1.0"?>
<config xmlns="http://uv.mx/hlimon"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://uv.mx/hlimon sys.xsd">

<name>Triplet Tree</name>

<agents>
  <agent>
    <program>contactPerson</program>
    <file>../sampleProtocols/tripletTree/contactPerson.asl</file>
  </agent>
   <agent>
    <program>worker</program>
    <file>../sampleProtocols/tripletTree/worker.asl</file>
  </agent>
</agents>
  <params>
    <param>
      <name>Base Classifier</name>
      <type>string</type>
    </param>
    <param>
      <name>Counter Classifier</name>
      <type>string</type>
    </param>
    <param>
      <name>Threads per node</name>
      <type>int</type>
    </param>
      <param>
    <name>Stratify</name>
    <type>boolean</type>
  </param>
    
  </params>
</config>

=== xl666/jaca-ddm/node0/config/proto.xml
<?xml version="1.0"?>
<config xmlns="http://uv.mx/hlimon"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://uv.mx/hlimon sys.xsd">

<name>contraEjemplos</name>

<agents>
  <agent>
    <program>coordinator</program>
    <file>./asl/coordinator.asl</file>
  </agent>
  <agent>
    <program>worker</program>
    <file>./asl/worker.asl</file>
  </agent>
  <agent>
    <program>linker</program>
    <file>./asl/lynker.asl</file>
  </agent>
</agents>

<params>
  <param>
    <name>numReps</name>
    <type>int</type>
  </param>
</params>

</config>

=== xl666/jaca-ddm/sampleProtocols/centralizedJ48/centralized.xml
<?xml version="1.0"?>
<config xmlns="http://uv.mx/hlimon"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://uv.mx/hlimon sys.xsd">

<name>centralized J48</name>

<agents>
  <agent>
    <program>contactPerson</program>
    <file>../sampleProtocols/centralizedj48/contactPerson.asl</file>
  </agent>
</agents>

<params>
  <param>
    <name>Pruning</name>
    <type>boolean</type>
  </param>
</params>

</config>

=== xl666/jaca-ddm/node0/prueba.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><config xmlns="http://uv.mx/hlimon" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://uv.mx/hlimon sys.xsd"><server><ip>192.168.0.100</ip></server><clients><client><name>c1</name><ip>localhost:8080</ip><file>/tmp/train1</file></client></clients><protocol><file>/home/xl666/Dropbox/doctorado/tesis/sistema/src/sampleProtocols/centralized/centralized.xml</file></protocol><distribution><agents><type>linker</type><client>c1</client><number>1</number></agents></distribution><evaluation><name>Cross-Validation</name><typeDataSource>Round files</typeDataSource><params><param><name>dataSet</name><value>/home/xl666/datasets/australian.arff</value><type>string</type></param><param><name>folds</name><value>10</value><type>int</type></param><param><name>repetitions</name><value>10</value><type>int</type></param><param><name>testPath</name><value>/tmp/test</value><type>string</type></param></params></evaluation></config>

=== xl666/jaca-ddm/sampleProtocols/baggingEnsemble/baggingEnsemble.xml
<?xml version="1.0"?>
<config xmlns="http://uv.mx/hlimon"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://uv.mx/hlimon sys.xsd">

<name>Bagging Ensemble</name>

<agents>
  <agent>
    <program>contactPerson</program>
    <file>../sampleProtocols/baggingEnsemble/contactPerson.asl</file>
  </agent>
   <agent>
    <program>bagger</program>
    <file>../sampleProtocols/baggingEnsemble/bagger.asl</file>
  </agent>
</agents>
  <params>
    <param>
      <name>Models per node</name>
      <type>int</type>
    </param>
    <param>
      <name>Threads per node</name>
      <type>int</type>
    </param>
    <param>
      <name>Classifier</name>
      <type>string</type>
    </param>
    <param>
      <name>Classifier parameters</name>
      <type>string</type>
    </param>
  </params>

</config>
